# 使用 Python 官方映像作為基礎映像
FROM python:3.7

# 複製 requirements.txt 到容器內的根目錄
COPY requirements.txt /app/

# 設置工作目錄
WORKDIR /app

# 安裝 Flask 和相關套件，包含 pymysql
RUN pip install Flask pymysql
RUN pip install email_validator
RUN pip install cryptography


# 安裝 requirements.txt 中列出的模組
RUN pip install -r requirements.txt

# 複製 run.py 和 app 目錄到容器內的根目錄
COPY run.py /app/
COPY app /app/app
COPY config.py /app/config.py

# 運行 Flask 應用程式
CMD ["python", "run.py"]
